export interface Product {
  id: string
  name: string
  category: string
  tagline: string
  description: string
  image: string
  price: string
  specs: {
    label: string
    value: string
  }[]
  features: string[]
}

export const products: Product[] = [
  {
    id: 'teak-platform-custom',
    name: 'Teak Platform Custom',
    category: 'Platforms',
    tagline: 'Built exactly to your brief',
    description: 'No standard size fits every yacht. The Teak Platform Custom is designed from scratch around your vessel — custom dimensions, shape, connection points, and cover finish. Our team handles every detail from brief to delivery.',
    image: '/images/product-teak-platform.png',
    price: 'Price on request',
    specs: [
      { label: 'Dimensions', value: 'Fully bespoke' },
      { label: 'Capacity', value: '100 kg/m²' },
      { label: 'Cover', value: 'Teak-print non-slip' },
      { label: 'Lead Time', value: 'On request' },
    ],
    features: ['Custom dimensions and shape', 'Bespoke connection points', 'Optional branding', 'Global delivery & service'],
  },
  {
    id: 'teak-platform-2x1',
    name: 'Teak Platform 2×1',
    category: 'Platforms',
    tagline: 'Compact teak elegance',
    description: 'Our smallest teak platform — perfect as a compact boarding step or single-person sun pad. The teak-print non-slip cover delivers luxury aesthetics with zero maintenance.',
    image: '/images/product-teak-platform.png',
    price: 'From €2,900',
    specs: [
      { label: 'Dimensions', value: '2m × 1m' },
      { label: 'Capacity', value: '100 kg/m²' },
      { label: 'Cover', value: 'Teak-print non-slip' },
      { label: 'Setup Time', value: '< 3 minutes' },
    ],
    features: ['Teak-print removable cover', 'Soft connection loops', 'Covered valves', 'Compact carry bag'],
  },
  {
    id: 'teak-platform-2x2',
    name: 'Teak Platform 2×2',
    category: 'Platforms',
    tagline: 'The versatile square',
    description: 'A perfectly balanced square platform ideal for tender boarding, snorkelling access, or a personal sun terrace. The teak-print cover adds superyacht-grade finish to every anchorage.',
    image: '/images/product-teak-platform.png',
    price: 'From €4,200',
    specs: [
      { label: 'Dimensions', value: '2m × 2m' },
      { label: 'Capacity', value: '100 kg/m²' },
      { label: 'Cover', value: 'Teak-print non-slip' },
      { label: 'Setup Time', value: '< 4 minutes' },
    ],
    features: ['Teak-print removable cover', 'Integrated carry handles', 'Covered valves', 'Compact carry bag'],
  },
  {
    id: 'teak-platform-3x2',
    name: 'Teak Platform 3×2',
    category: 'Platforms',
    tagline: 'Room for the whole crew',
    description: 'A generously sized platform that comfortably seats four to six guests. Ideal for al-fresco lunches at water level, water toy staging, or a dedicated swim area.',
    image: '/images/product-teak-platform.png',
    price: 'From €5,800',
    specs: [
      { label: 'Dimensions', value: '3m × 2m' },
      { label: 'Capacity', value: '100 kg/m²' },
      { label: 'Cover', value: 'Teak-print non-slip' },
      { label: 'Setup Time', value: '< 5 minutes' },
    ],
    features: ['Teak-print removable cover', 'Dual carry handles', 'Reinforced connection points', 'UV-resistant materials'],
  },
  {
    id: 'teak-platform-4x2',
    name: 'Teak Platform 4×2',
    category: 'Platforms',
    tagline: 'The entertainer',
    description: 'Eight square metres of pure floating luxury — large enough to host cocktails, yoga, or a water-level dining experience. A true beach club extension for any superyacht.',
    image: '/images/product-teak-platform.png',
    price: 'From €7,400',
    specs: [
      { label: 'Dimensions', value: '4m × 2m' },
      { label: 'Capacity', value: '100 kg/m²' },
      { label: 'Cover', value: 'Teak-print non-slip' },
      { label: 'Setup Time', value: '< 6 minutes' },
    ],
    features: ['Teak-print removable cover', 'Multiple D-ring anchor points', 'Covered valves', 'Bespoke branding available'],
  },
  {
    id: 'teak-platform-6x2',
    name: 'Teak Platform 6×2',
    category: 'Platforms',
    tagline: 'Flagship floating deck',
    description: 'Twelve square metres of seamless floating surface — our flagship teak platform designed to transform any anchorage into a private beach club. Sets up in under ten minutes.',
    image: '/images/product-teak-platform.png',
    price: 'From €10,200',
    specs: [
      { label: 'Dimensions', value: '6m × 2m' },
      { label: 'Capacity', value: '100 kg/m²' },
      { label: 'Cover', value: 'Teak-print non-slip' },
      { label: 'Setup Time', value: '< 10 minutes' },
    ],
    features: ['Teak-print removable cover', 'Full perimeter D-rings', 'Covered valves', 'Global service support'],
  },
  {
    id: 'teak-platform-8x2',
    name: 'Teak Platform 8×2',
    category: 'Platforms',
    tagline: 'The ultimate runway',
    description: 'Our largest single-piece teak platform — sixteen square metres of floating deck space for the most ambitious beach club setups. Engineered for expedition yachts and charter flagships.',
    image: '/images/product-teak-platform.png',
    price: 'From €13,500',
    specs: [
      { label: 'Dimensions', value: '8m × 2m' },
      { label: 'Capacity', value: '100 kg/m²' },
      { label: 'Cover', value: 'Teak-print non-slip' },
      { label: 'Setup Time', value: '< 12 minutes' },
    ],
    features: ['Teak-print removable cover', 'Heavy-duty anchor system', 'Bespoke branding available', 'Global service support'],
  },
  {
    id: 'hex-platform',
    name: 'Hex Platform',
    category: 'Hexes',
    tagline: 'Pure hexagonal simplicity',
    description: 'A clean, single-hex inflatable platform with a teak-print deck surface. The Hex Platform is the essential building block of any Xflatable hex configuration — standalone or as part of a larger array.',
    image: '/images/product-hex-platform.png',
    price: 'From €4,500',
    specs: [
      { label: 'Shape', value: 'Hexagonal' },
      { label: 'Diameter', value: '2.4m flat-to-flat' },
      { label: 'Cover', value: 'Teak-print non-slip' },
      { label: 'Setup Time', value: '< 3 minutes' },
    ],
    features: ['Teak-print removable cover', 'Interlocking hex connectors', 'Lightweight compact pack size', 'Fully modular'],
  },
  {
    id: 'hex-lounge',
    name: 'Hex Lounge',
    category: 'Hexes',
    tagline: 'Your floating living room',
    description: 'The Hex Lounge combines a hexagonal teak platform with integrated inflatable sofa seating around the perimeter, creating a self-contained floating lounge for six to eight guests.',
    image: '/images/product-hex-lounge.png',
    price: 'From €7,900',
    specs: [
      { label: 'Shape', value: 'Hexagonal' },
      { label: 'Diameter', value: '3.2m flat-to-flat' },
      { label: 'Seating', value: '6–8 guests' },
      { label: 'Setup Time', value: '< 8 minutes' },
    ],
    features: ['Integrated inflatable sofa', 'Teak-print deck centre', 'Connectable to Hex arrays', 'UV-resistant upholstery'],
  },
  {
    id: 'hex-single',
    name: 'Hex Single',
    category: 'Hexes',
    tagline: 'The versatile single-hex module',
    description:
      'The Hex Single is our core hexagonal platform module — a lightweight, interlocking unit that creates striking honeycomb layouts at the water\'s edge. Ideal as a standalone sun deck or the foundation for a larger Hex array.',
    image: '/images/hex-platforms-2.png',
    price: 'From €3,800',
    specs: [
      { label: 'Shape', value: 'Hexagonal' },
      { label: 'Diameter', value: '2.4m flat-to-flat' },
      { label: 'Capacity', value: '100 kg/m²' },
      { label: 'Setup Time', value: '< 3 minutes' },
    ],
    features: [
      'Interlocking hex connectors',
      'Non-slip deck surface',
      'Lightweight compact pack size',
      'Fully modular — grow your layout',
    ],
  },
  {
    id: 'hex-tub',
    name: 'Hex Tub',
    category: 'Hexes',
    tagline: 'A floating hot tub at sea',
    description: 'The Hex Tub transforms a hexagonal platform into a private floating jacuzzi experience. A recessed central tub is surrounded by a teak-print deck, creating the ultimate water-level amenity.',
    image: '/images/product-hex-tub.png',
    price: 'From €14,900',
    specs: [
      { label: 'Shape', value: 'Hexagonal' },
      { label: 'Diameter', value: '3.6m flat-to-flat' },
      { label: 'Tub Capacity', value: '4–6 persons' },
      { label: 'Setup Time', value: '< 15 minutes' },
    ],
    features: ['Recessed central tub', 'Teak-print deck surround', 'Connectable to Hex arrays', 'Optional heating system'],
  },
  {
    id: 'hex-platform-custom',
    name: 'Hex Platform Custom',
    category: 'Hexes',
    tagline: 'Bespoke hexagonal geometry',
    description: 'Custom hexagonal platforms designed to your exact specifications. Whether you need a unique size, specialized connection points, or integrated accessories, the Hex Platform Custom is engineered from brief to delivery. Perfect for one-off installations or flagship layouts.',
    image: '/images/product-hex-platform.png',
    price: 'Price on request',
    specs: [
      { label: 'Shape', value: 'Fully custom hexagonal' },
      { label: 'Diameter', value: 'Bespoke' },
      { label: 'Cover', value: 'Custom finish options' },
      { label: 'Lead Time', value: 'On request' },
    ],
    features: ['Custom dimensions and geometry', 'Bespoke connection systems', 'Optional integrated accessories', 'Global delivery & service'],
  },
  {
    id: 'hex-array',
    name: 'Hex Array',
    category: 'Hexes',
    tagline: 'Honeycomb luxury at scale',
    description:
      'Connect multiple Hex Singles to create a dramatic, large-format floating surface. The Hex Array is perfect for superyacht beach clubs, water-level lounges, and bespoke swim areas — configurable to any shape or size.',
    image: '/images/hex-platforms-2.png',
    price: 'From €10,500',
    specs: [
      { label: 'Configuration', value: 'Fully custom' },
      { label: 'Min. Array', value: '3 modules' },
      { label: 'Capacity', value: '100 kg/m²' },
      { label: 'Setup Time', value: '< 10 minutes' },
    ],
    features: [
      'Unlimited expansion',
      'Rigid inter-module locking',
      'Even weight distribution',
      'Optional anchor kit included',
    ],
  },
  {
    id: 'seapool-4x4',
    name: 'Seapool 4×4',
    category: 'Seapool',
    tagline: 'Compact personal swim space',
    description: 'The 4×4 Seapool creates an intimate enclosed swim area perfect for protected bathing and water activities. Ideal for charter yachts and private vessels seeking a contained aquatic environment at any anchorage.',
    image: '/images/product-seapool.png',
    price: 'From €6,800',
    specs: [
      { label: 'Dimensions', value: '4m × 4m' },
      { label: 'Capacity', value: '20–30 people' },
      { label: 'Mesh', value: 'UV-resistant net walls' },
      { label: 'Setup Time', value: '< 15 minutes' },
    ],
    features: ['Enclosed mesh perimeter', 'Contained swim area', 'Easy anchor system', 'Compact storage bag'],
  },
  {
    id: 'seapool-4x6',
    name: 'Seapool 4×6',
    category: 'Seapool',
    tagline: 'The versatile swim enclosure',
    description: 'A spacious rectangular seapool ideal for families and groups. The 4×6 Seapool provides ample swimming and recreational space while maintaining a contained, protected environment perfect for marine conservation-conscious yachts.',
    image: '/images/product-seapool.png',
    price: 'From €8,200',
    specs: [
      { label: 'Dimensions', value: '4m × 6m' },
      { label: 'Capacity', value: '40–60 people' },
      { label: 'Mesh', value: 'Heavy-duty UV-resistant net' },
      { label: 'Setup Time', value: '< 18 minutes' },
    ],
    features: ['Generous swim area', 'Reinforced mesh walls', 'Multiple entry points', 'Professional anchor kit'],
  },
  {
    id: 'seapool-custom',
    name: 'Seapool Custom',
    category: 'Seapool',
    tagline: 'Bespoke enclosed swim sanctuary',
    description: 'Design your perfect seapool from scratch. The Seapool Custom is engineered to your exact dimensions, mesh specifications, and operational needs — from intimate enclosed pools to large-scale marine habitats.',
    image: '/images/product-seapool.png',
    price: 'Price on request',
    specs: [
      { label: 'Dimensions', value: 'Fully bespoke' },
      { label: 'Capacity', value: 'Custom' },
      { label: 'Mesh Options', value: 'Multiple grades available' },
      { label: 'Lead Time', value: 'On request' },
    ],
    features: ['Custom dimensions & shape', 'Specialized mesh options', 'Integrated access points', 'Global delivery & installation'],
  },
]

export const categories = [
  { id: 'all', name: 'All' },
  { id: 'platforms', name: 'Platforms' },
  { id: 'hexes', name: 'Hexes' },
  { id: 'seapool', name: 'Seapool' },
]
